[package]
name = "dep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.15.4"

[profile.release]
strip = true
panic = "abort"
lto = true
opt-level = "z"
